#!/bin/bash
set -e

function die()
{
  echo "fatal: " "$@"
  exit 1
}

if [ $# -lt 2 ]
then
  die "syntax: $0 <index_name> <doc_id>"
fi

if [ -z "${ELASTIC_URL}" ]
then
  die "Missing elasticsearch URL"
fi

index_name=$1
doc_id=$2

convert_args=()
convert_args+=(-density 300)
convert_args+=(-depth 8)
convert_args+=(-background white)
convert_args+=(-alpha off)
convert_args+=(-strip)

convert "${convert_args[@]}" - temp.tiff
tesseract temp.tiff stdout \
  | grep -v '^ *$' \
  | jq -R -s '{"content": tostring}' \
  > temp.json
# ideally would pipe through curl but this avoids the risk of timing out
curl -X PUT -d @temp.json \
  -H 'Content-Type: application/json' \
  "${ELASTIC_URL}/${index_name}/doc/${doc_id}?pretty"
